### ISSUE TITLE
TODO For release

### ISSUE THREAD

**Issue by RangerMauve** [consento-org/rn-tape#1]
Here's the TODOs for the initial release

- [x] Merge code from get-random-values-polypony into repo
  - [x] Copy over RNTape and ExpoTape
  - [x] Copy over react-native CLI util
  - [x] Wrap everything with yargs
- [x] Create example project / get CLI working with it: https://github.com/consento-org/rn-tape-example
- [x] Initial code review / corrections
- [x] Clean up CLI output and make sure it's TAP compatible
- [x] Add it to get-random-values-polypony
- [x] Document all flags / env vars.
- [ ] Support configurable RN and Expo versions. #20

**Comment by martinheidegger** [comment]
What is missing here?

**Comment by RangerMauve** [comment]
I guess it's ready, I could release it after #17

**Comment by RangerMauve** [comment]
Just released rn-tape@1.0.0-4

@martinheidegger Do you think we're ready for 1.0.0 proper?

**Comment by martinheidegger** [comment]
Creating a way to support different react-native version (#20) would be good for general usefulness.
